spring.profiles.active: local

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/management?useSSL=false
    username: root
    password: Seguridad_6
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/.well-known/jwks.json

logging:
  level:
    root: INFO

app:
  config:
    key: "7FF6936DE688EC87D52C522C7E878FCFF0B0599DD7CB30E8C2073422FFB63BD9"