spring.profiles.active: local

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
  jpa:
    database-platform: ${DATABASE_DIALECT}
    hibernate:
      ddl-auto: ${DATABASE_DDL}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SECURITY_JWK_URL}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT}